apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 2

  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 30 }
      - setWeight: 50
      - pause: { duration: 30 }
      - setWeight: 100

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
<<<<<<< HEAD
      - name: demo
        image: vashishtd/demo-app:423435e770a197a66abcc03be061028f5845c333
=======
      - name: demo-app
        image: vashishtd/demo-app:423435e770a197a66abcc03be061028f5845c333
>>>>>>> ea2ca05 (Canary Deployment with Argo Rollouts)
        ports:
        - containerPort: 80