apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: vashishtd/demo-app:0b8a597ddb3fca5f2e5031fef575be1f114f3d41
        ports:
        - containerPort: 80