name: CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DOCKER_USER: vashishtd
  IMAGE_NAME: demo-app

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'Update image')"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USER/$IMAGE_NAME:${{ github.sha }} .

    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USER --password-stdin

    - name: Push Docker image
      run: |
        docker push $DOCKER_USER/$IMAGE_NAME:${{ github.sha }}

    - name: Update deployment.yaml
      run: |
        sed -i "s|IMAGE_TAG|${{ github.sha }}|" deployment.yaml

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add deployment.yaml
        git commit -m "Update image to ${{ github.sha }}" || echo "No changes"
        git push